// Localization tiếng Việt cho Clerk
export const viVN = {
  locale: "vi-VN",
  
  // Sign In
  "signIn.start.title": "Đăng nhập vào QuickStay",
  "signIn.start.emailInputLabel": "Địa chỉ email",
  "signIn.start.emailInputPlaceholder": "Nhập địa chỉ email của bạn",
  "signIn.start.submitButton": "Tiếp tục",
  "signIn.start.dividerLabel": "hoặc",
  "signIn.start.socialButtonsBlockButton": "Tiếp tục với {{provider}}",
  "signIn.start.socialButtonsBlockButton__google": "Tiếp tục với Google",
  "signIn.start.alternativeMethods.title": "Sử dụng phương thức khác",
  "signIn.start.alternativeMethods.actionLink": "Không có tài khoản?",
  "signIn.start.alternativeMethods.blockButton__signUp": "Đăng ký",
  
  // Sign Up
  "signUp.start.title": "Tạo tài khoản QuickStay",
  "signUp.start.emailInputLabel": "Địa chỉ email",
  "signUp.start.emailInputPlaceholder": "Nhập địa chỉ email của bạn",
  "signUp.start.submitButton": "Tiếp tục",
  "signUp.start.dividerLabel": "hoặc",
  "signUp.start.socialButtonsBlockButton": "Tiếp tục với {{provider}}",
  "signUp.start.socialButtonsBlockButton__google": "Tiếp tục với Google",
  "signUp.start.alternativeMethods.title": "Đã có tài khoản?",
  "signUp.start.alternativeMethods.actionLink": "Đăng nhập",
  
  // Email Code
  "emailCode.form.title": "Mã xác minh",
  "emailCode.form.codeInputLabel": "Mã xác minh",
  "emailCode.form.codeInputPlaceholder": "Nhập mã xác minh",
  "emailCode.form.submitButton": "Tiếp tục",
  "emailCode.form.resendButton": "Gửi lại mã",
  "emailCode.form.resendButton__loading": "Đang gửi lại...",
  
  // Password
  "password.form.title": "Nhập mật khẩu của bạn",
  "password.form.passwordInputLabel": "Mật khẩu",
  "password.form.passwordInputPlaceholder": "Nhập mật khẩu của bạn",
  "password.form.submitButton": "Tiếp tục",
  "password.form.forgotPasswordButton": "Quên mật khẩu?",
  
  // Forgot Password
  "forgotPassword.form.title": "Đặt lại mật khẩu",
  "forgotPassword.form.emailInputLabel": "Địa chỉ email",
  "forgotPassword.form.emailInputPlaceholder": "Nhập địa chỉ email của bạn",
  "forgotPassword.form.submitButton": "Gửi liên kết đặt lại",
  "forgotPassword.form.backButton": "Quay lại",
  
  // Common
  "formFieldLabel__emailAddress": "Địa chỉ email",
  "formFieldLabel__emailAddresses": "Địa chỉ email",
  "formFieldLabel__password": "Mật khẩu",
  "formFieldLabel__currentPassword": "Mật khẩu hiện tại",
  "formFieldLabel__newPassword": "Mật khẩu mới",
  "formFieldLabel__confirmPassword": "Xác nhận mật khẩu",
  "formFieldLabel__phoneNumber": "Số điện thoại",
  "formFieldLabel__username": "Tên người dùng",
  "formFieldLabel__firstName": "Tên",
  "formFieldLabel__lastName": "Họ",
  "formFieldInputPlaceholder__emailAddress": "Nhập địa chỉ email của bạn",
  "formFieldInputPlaceholder__password": "Nhập mật khẩu của bạn",
  "formFieldInputPlaceholder__phoneNumber": "Nhập số điện thoại của bạn",
  "formFieldInputPlaceholder__username": "Nhập tên người dùng của bạn",
  "formFieldInputPlaceholder__firstName": "Nhập tên của bạn",
  "formFieldInputPlaceholder__lastName": "Nhập họ của bạn",
  "formFieldError__matchingPasswords": "Mật khẩu không khớp",
  "formFieldError__minLength": "Tối thiểu {{count}} ký tự",
  "formFieldError__maxLength": "Tối đa {{count}} ký tự",
  "formFieldError__required": "Trường này là bắt buộc",
  "formFieldError__emailAddress": "Địa chỉ email không hợp lệ",
  "formFieldError__phoneNumber": "Số điện thoại không hợp lệ",
  "formButtonPrimary": "Tiếp tục",
  "formButtonReset": "Đặt lại",
  "formButtonSecondary": "Hủy",
  "formFieldHintText__optional": "Tùy chọn",
  "formFieldHintText__slug": "URL sẽ là:",
  "formFieldHintText__username": "Tên người dùng có thể chứa chữ cái, số và dấu gạch dưới",
  "badge__default": "Mặc định",
  "badge__unverified": "Chưa xác minh",
  "badge__requiresAction": "Yêu cầu hành động",
  "badge__you": "Bạn",
  "footerPageLink__help": "Trợ giúp",
  "footerPageLink__privacy": "Quyền riêng tư",
  "footerPageLink__terms": "Điều khoản",
  "footerActionLink__signIn": "Đăng nhập",
  "footerActionLink__signUp": "Đăng ký",
  "footerActionLink__skip": "Bỏ qua",
  "paginationButton__previous": "Trước",
  "paginationButton__next": "Tiếp",
  "paginationRowText__displaying": "Hiển thị",
  "paginationRowText__of": "của",
  "memberProfilePage.title": "Hồ sơ",
  "memberProfilePage.backButton": "Quay lại",
  "memberProfilePage.saveButton": "Lưu",
  "memberProfilePage.cancelButton": "Hủy",
  "memberProfilePage.editButton": "Chỉnh sửa",
  "memberProfilePage.deleteButton": "Xóa",
  "memberProfilePage.dangerSectionTitle": "Nguy hiểm",
  "memberProfilePage.dangerSectionDescription": "Các hành động này không thể hoàn tác",
  "memberProfilePage.dangerSectionDeleteButton": "Xóa tài khoản",
  "memberProfilePage.dangerSectionDeleteButtonDescription": "Xóa tài khoản của bạn và tất cả dữ liệu liên quan",
  "memberProfilePage.dangerSectionDeleteButtonConfirmation": "Bạn có chắc chắn muốn xóa tài khoản của mình không?",
  "memberProfilePage.dangerSectionDeleteButtonConfirmationDescription": "Hành động này không thể hoàn tác",
  "memberProfilePage.dangerSectionDeleteButtonConfirmationCancel": "Hủy",
  "memberProfilePage.dangerSectionDeleteButtonConfirmationConfirm": "Xóa tài khoản",
  "memberProfilePage.dangerSectionDeleteButtonConfirmationTitle": "Xóa tài khoản",
  "userButton.menu.signOut": "Đăng xuất",
  "userButton.menu.account": "Tài khoản",
  "userButton.menu.settings": "Cài đặt",
  "userButton.menu.manageAccount": "Quản lý tài khoản",
  "userButton.menu.profile": "Hồ sơ",
  "userButton.menu.signIn": "Đăng nhập",
  "userButton.menu.signUp": "Đăng ký",
  "userButton.menu.userButton": "Nút người dùng",
  "userButton.menu.userButtonMenu": "Menu nút người dùng",
  "userButton.menu.userButtonPopover": "Popover nút người dùng",
  "userButton.menu.userButtonPopoverActions": "Hành động popover nút người dùng",
  "userButton.menu.userButtonPopoverFooter": "Footer popover nút người dùng",
  "userButton.menu.userButtonPopoverHeader": "Header popover nút người dùng",
  "userButton.menu.userButtonPopoverMainIdentifier": "Định danh chính popover nút người dùng",
  "userButton.menu.userButtonPopoverSecondaryIdentifier": "Định danh phụ popover nút người dùng",
  "userButton.menu.userButtonPopoverSubtitle": "Phụ đề popover nút người dùng",
  "userButton.menu.userButtonPopoverTitle": "Tiêu đề popover nút người dùng",
  "userButtonPopover.actions.addAccount": "Thêm tài khoản",
  "userButtonPopover.actions.manageAccount": "Quản lý tài khoản",
  "userButtonPopover.actions.signOut": "Đăng xuất",
  "userButtonPopover.actions.signOutAll": "Đăng xuất tất cả",
  "userButtonPopover.footer.manageAccount": "Quản lý tài khoản",
  "userButtonPopover.footer.signOut": "Đăng xuất",
  "userButtonPopover.header.account": "Tài khoản",
  "userButtonPopover.header.settings": "Cài đặt",
  "userButtonPopover.mainIdentifier": "Định danh chính",
  "userButtonPopover.secondaryIdentifier": "Định danh phụ",
  "userButtonPopover.subtitle": "Phụ đề",
  "userButtonPopover.title": "Tiêu đề",
  "errors.alreadySignedIn": "Bạn đã đăng nhập",
  "errors.codeExpired": "Mã đã hết hạn",
  "errors.formCodeIncorrect": "Mã không chính xác",
  "errors.formEmailAddressNotVerified": "Địa chỉ email chưa được xác minh",
  "errors.formFieldRequired": "Trường này là bắt buộc",
  "errors.formFieldValue__emailAddress": "Địa chỉ email không hợp lệ",
  "errors.formFieldValue__phoneNumber": "Số điện thoại không hợp lệ",
  "errors.formPasswordIncorrect": "Mật khẩu không chính xác",
  "errors.formPasswordLengthToShort": "Mật khẩu quá ngắn",
  "errors.formPasswordNotLongEnough": "Mật khẩu không đủ dài",
  "errors.formPasswordPwned": "Mật khẩu này đã bị xâm phạm",
  "errors.formPasswordSizeInBytesExceeded": "Mật khẩu quá dài",
  "errors.formPasswordValidationFailed": "Xác thực mật khẩu thất bại",
  "errors.formPasswordWeak": "Mật khẩu quá yếu",
  "errors.formUsernameInvalid": "Tên người dùng không hợp lệ",
  "errors.formUsernameInvalidCharacter": "Tên người dùng chứa ký tự không hợp lệ",
  "errors.formUsernameInvalidLength": "Tên người dùng không đủ dài",
  "errors.formUsernameTaken": "Tên người dùng đã được sử dụng",
  "errors.identificationDeletionFailed": "Xóa định danh thất bại",
  "errors.identificationDeletionFailed__primary": "Không thể xóa định danh chính",
  "errors.identificationDeletionFailed__last": "Không thể xóa định danh cuối cùng",
  "errors.notFound": "Không tìm thấy",
  "errors.somethingWentWrong": "Đã xảy ra lỗi",
  "errors.submitButton": "Thử lại",
  "errors.userLocked": "Tài khoản của bạn đã bị khóa",
  "errors.userNotFound": "Không tìm thấy người dùng",
  "footerPageLink__help": "Trợ giúp",
  "footerPageLink__privacy": "Quyền riêng tư",
  "footerPageLink__terms": "Điều khoản",
  "footerActionLink__signIn": "Đăng nhập",
  "footerActionLink__signUp": "Đăng ký",
  "footerActionLink__skip": "Bỏ qua",
  "formFieldLabel__emailAddress": "Địa chỉ email",
  "formFieldLabel__emailAddresses": "Địa chỉ email",
  "formFieldLabel__password": "Mật khẩu",
  "formFieldLabel__currentPassword": "Mật khẩu hiện tại",
  "formFieldLabel__newPassword": "Mật khẩu mới",
  "formFieldLabel__confirmPassword": "Xác nhận mật khẩu",
  "formFieldLabel__phoneNumber": "Số điện thoại",
  "formFieldLabel__username": "Tên người dùng",
  "formFieldLabel__firstName": "Tên",
  "formFieldLabel__lastName": "Họ",
  "formFieldInputPlaceholder__emailAddress": "Nhập địa chỉ email của bạn",
  "formFieldInputPlaceholder__password": "Nhập mật khẩu của bạn",
  "formFieldInputPlaceholder__phoneNumber": "Nhập số điện thoại của bạn",
  "formFieldInputPlaceholder__username": "Nhập tên người dùng của bạn",
  "formFieldInputPlaceholder__firstName": "Nhập tên của bạn",
  "formFieldInputPlaceholder__lastName": "Nhập họ của bạn",
  "formFieldError__matchingPasswords": "Mật khẩu không khớp",
  "formFieldError__minLength": "Tối thiểu {{count}} ký tự",
  "formFieldError__maxLength": "Tối đa {{count}} ký tự",
  "formFieldError__required": "Trường này là bắt buộc",
  "formFieldError__emailAddress": "Địa chỉ email không hợp lệ",
  "formFieldError__phoneNumber": "Số điện thoại không hợp lệ",
  "formButtonPrimary": "Tiếp tục",
  "formButtonReset": "Đặt lại",
  "formButtonSecondary": "Hủy",
  "formFieldHintText__optional": "Tùy chọn",
  "formFieldHintText__slug": "URL sẽ là:",
  "formFieldHintText__username": "Tên người dùng có thể chứa chữ cái, số và dấu gạch dưới",
  "badge__default": "Mặc định",
  "badge__unverified": "Chưa xác minh",
  "badge__requiresAction": "Yêu cầu hành động",
  "badge__you": "Bạn",
  "paginationButton__previous": "Trước",
  "paginationButton__next": "Tiếp",
  "paginationRowText__displaying": "Hiển thị",
  "paginationRowText__of": "của",
};

