// Dữ liệu quận/huyện cho các thành phố ở Việt Nam
export const districts = {
  "Hà Nội": [
    "Quận Ba Đình",
    "Quận Hoàn Kiếm",
    "Quận Tây Hồ",
    "Quận Long Biên",
    "Quận Cầu Giấy",
    "Quận Đống Đa",
    "Quận Hai Bà Trưng",
    "Quận Hoàng Mai",
    "Quận Thanh Xuân",
    "Huyện Sóc Sơn",
    "Huyện Đông Anh",
    "Huyện Gia Lâm",
    "Huyện Nam Từ Liêm",
    "Huyện Bắc Từ Liêm",
    "Huyện Mê Linh",
    "Huyện Hà Đông",
    "Huyện Sơn Tây",
    "Huyện Ba Vì",
    "Huyện Phúc Thọ",
    "Huyện Đan Phượng",
    "Huyện Hoài Đức",
    "Huyện Quốc Oai",
    "Huyện Thạch Thất",
    "Huyện Chương Mỹ",
    "Huyện Thanh Oai",
    "Huyện Thường Tín",
    "Huyện Phú Xuyên",
    "Huyện Ứng Hòa",
    "Huyện Mỹ Đức"
  ],
  "Hồ Chí Minh": [
    "Quận 1",
    "Quận 2",
    "Quận 3",
    "Quận 4",
    "Quận 5",
    "Quận 6",
    "Quận 7",
    "Quận 8",
    "Quận 9",
    "Quận 10",
    "Quận 11",
    "Quận 12",
    "Quận Bình Thạnh",
    "Quận Tân Bình",
    "Quận Tân Phú",
    "Quận Phú Nhuận",
    "Quận Thủ Đức",
    "Quận Bình Tân",
    "Quận Gò Vấp",
    "Huyện Bình Chánh",
    "Huyện Cần Giờ",
    "Huyện Củ Chi",
    "Huyện Hóc Môn",
    "Huyện Nhà Bè"
  ],
  "Đà Nẵng": [
    "Quận Hải Châu",
    "Quận Thanh Khê",
    "Quận Sơn Trà",
    "Quận Ngũ Hành Sơn",
    "Quận Liên Chiểu",
    "Quận Cẩm Lệ",
    "Huyện Hòa Vang",
    "Huyện Hoàng Sa"
  ],
  "Hải Phòng": [
    "Quận Hồng Bàng",
    "Quận Ngô Quyền",
    "Quận Lê Chân",
    "Quận Hải An",
    "Quận Kiến An",
    "Quận Đồ Sơn",
    "Quận Dương Kinh",
    "Huyện Thuỷ Nguyên",
    "Huyện An Dương",
    "Huyện An Lão",
    "Huyện Kiến Thuỵ",
    "Huyện Tiên Lãng",
    "Huyện Vĩnh Bảo",
    "Huyện Cát Hải",
    "Huyện Bạch Long Vĩ"
  ]
};

